// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oimcyxhalzbetmdvjgbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pbWN5eGhhbHpiZXRtZHZqZ2JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNDAwMTgsImV4cCI6MjA3MzYxNjAxOH0.32cvQw4tRmXYF5Lsua0ZQ_qxZ1Lf7NHaYPCzXNRpKMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});